yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: node-modules

unsafeHttpWhitelist:
  - "npm.greensock.com"

npmScopes:
  fiap:
    npmRegistryServer: https://gitlab.fiap.com.br/api/v4/projects/173/packages/npm/
    npmAlwaysAuth: true
    npmAuthToken: ${npm_auth_token}
  gsap:
    npmRegistryServer: "https://npm.greensock.com"
    npmAuthToken: ${gsap_auth_token}

